apiVersion: v1
kind: ConfigMap
metadata:
    name: genai-config
    namespace: team-promptheus
data:
      - GENAI_PORT=${GENAI_PORT:-3003}
      - OTEL_SERVICE_NAME="genai"
      - OTEL_EXPORTER_OTLP_TIMEOUT=5 # in seconds
      - OTEL_TRACES_SAMPLER="always_on"
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_METRICS_EXEMPLAR_FILTER=always_on
      - OTEL_LOG_LEVEL="debug"
