apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
    name: postgres-health-alerts
    namespace: team-promptheus
    labels:
        app: prometheus
        role: alert-rules
spec:
    groups:
    - name: postgres-health
      rules:
      - alert: PostgresDown
        expr: pg_up{namespace="team-promptheus"} == 0
        for: 1m
        labels:
            severity: critical
        annotations:
            summary: "PostgreSQL is down"
            description: "PostgreSQL database has been down for more than 1 minute"

      - alert: HighDatabaseConnections
        expr: pg_stat_database_numbackends{namespace="team-promptheus"} > 80
        for: 5m
        labels:
            severity: warning
        annotations:
            summary: "High number of database connections"
            description: "PostgreSQL has {{ $value }} active connections, which is approaching the limit"

      - alert: DatabaseConnectionsExhausted
        expr: pg_stat_database_numbackends{namespace="team-promptheus"} > 95
        for: 1m
        labels:
            severity: critical
        annotations:
            summary: "Database connections nearly exhausted"
            description: "PostgreSQL has {{ $value }} active connections, approaching maximum capacity"

      - alert: LongRunningQueries
        expr: pg_stat_activity_max_tx_duration{namespace="team-promptheus"} > 3600
        for: 1m
        labels:
            severity: warning
        annotations:
            summary: "Long running database queries detected"
            description: "PostgreSQL has queries running for more than 1 hour. Max duration: {{ $value }}s"
