# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
            args: [--allow-multiple-documents]
            exclude: "^k8s/.+$"
          - id: check-json
          - id: check-toml
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: debug-statements

    - repo: https://github.com/biomejs/pre-commit
      rev: "v2.0.5"
      hooks:
          - id: biome-format
            additional_dependencies: ["@biomejs/biome@2.0.5"]
          - id: biome-lint
            name: biome lint
            entry: biome check --formatter-enabled=false --linter-enabled=false --write --files-ignore-unknown=true --no-errors-on-unmatched
            language: node
            types: [text]
            files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$"
            require_serial: true
            additional_dependencies: ["@biomejs/biome@2.0.5"]
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.12.1
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format
