{
 "title": "Team Promptheus Application Dashboard",
 "tags": [
  "team-promptheus",
  "application"
 ],
 "time": { "from": "2025-07-20T20:49:58.785Z", "to": "2025-07-20T21:49:58.785Z" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{job=\"server-service\"})"
    }
   ]
  },
  {
   "title": "GenAI Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{job=\"genai-service\"})"
    }
   ]
  },
  {
   "title": "Search Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{job=\"search-service\"})"
    }
   ]
  },
  {
   "title": "Database Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{job=\"postgres-service\"})"
    }
   ]
  },
  {
   "title": "MeiliSearch Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{job=\"meilisearch-service\"})"
    }
   ]
  },
  {
   "title": "Contribution Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{job=\"contribution-service\"})"
    }
   ]
  },
  {
   "title": "Server reqeust seconds by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "avg(http_server_requests_seconds_max{})by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Number of active summaries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(genai_active_summaries_count{}[$__rate_interval]))",
     "legendFormat": "${metric} (overall per-second rate)"
    }
   ]
  },
  {
   "title": "Invocation seconds count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 12 },
   "targets": [
    {
     "expr": "sum(spring_data_repository_invocations_seconds_count)",
     "legendFormat": "${metric} (overall per-second rate)"
    }
   ]
  }
 ]
}