apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
  namespace: team-promptheus
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'webhook'
  receivers:
  - name: 'webhook'
    webhookConfigs:
    - url: 'https://webhook.site/94869a6f-2de8-4746-bc62-5b9f18aab716'
#    activeTimeIntervals:
#      - string
#    continue: boolean
#    groupBy:
#      - string
#    matchers:
#      - matchType: string
#        name: string
#        regex: boolean
#        value: string
#    muteTimeIntervals:
#      - string
#    receiver: string
#    routes:
#
#  inhibitRules:
#    - equal:
#        - string
#      sourceMatch:
#        - matchType: string
#          name: string
#          regex: boolean
#          value: string
#      targetMatch:
#        - matchType: string
#          name: string
#          regex: boolean
#          value: string
#  muteTimeIntervals:
#    - name: string
#      timeIntervals:
#        - daysOfMonth:
#            - end: int
#              start: int
#          months:
#            - string
#          times:
#            - endTime: string
#              startTime: string
#          weekdays:
#            - string
#          years:
#            - string
__clone: true
