apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-team-promptheus-prometheus
  namespace: {{ $.Release.Namespace }}
  labels:
    app: prometheus
    component: serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-team-promptheus-prometheus
  namespace: {{ $.Release.Namespace }}
  labels:
    app: prometheus
    component: role
rules:
  - apiGroups: [""]
    resources:
      - services
      - endpoints
      - pods
      - configmaps
      - secrets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - servicemonitors
      - podmonitors
      - prometheusrules
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-team-promptheus-prometheus
  namespace: {{ $.Release.Namespace }}
  labels:
    app: prometheus
    component: rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-team-promptheus-prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus-team-promptheus-prometheus
    namespace: {{ $.Release.Namespace }}
