-- Add GENERATED ALWAYS AS IDENTITY to git_repositories.id
ALTER TABLE git_repositories 
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- Add GENERATED ALWAYS AS IDENTITY to summaries.id  
ALTER TABLE summaries 
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- Add GENERATED ALWAYS AS IDENTITY to questions.id
ALTER TABLE questions 
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- Add GENERATED ALWAYS AS IDENTITY to question_answers.id
ALTER TABLE question_answers 
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY; 