# Development values for team-promptheus.

# Development secrets (insecure - for dev only)

defaultReplicas: 1

secrets:
  postgresPassword: "postgres"
  meiliMasterKey: "change_me_change_me_change_me"
ingress:
  domain: "team-prompteus.local"

# Storage configuration
storage:
  class: "csi-rbd-sc"

# Prometheus configuration
prometheus:
  enabled: true
  retention: "7d"
  storageSize: "5Gi"

# Alertmanager configuration
alertmanager:
  enabled: true
  storageSize: "1Gi"
