# Development values for team-promptheus.

# Development secrets (insecure - for dev only)

defaultReplicas: 1

secrets:
    postgresPassword: "postgres"
    meiliMasterKey: "change_me_change_me_change_me"
ingress:
    domain: "team-prompteus.local"
