apiVersion: v1
kind: Service
metadata:
    name: client-service
    namespace: team-promptheus
spec:
    selector:
        app: client
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
