apiVersion: v1
kind: Service
metadata:
  name: meilisearch-service
  namespace: team-promptheus
spec:
  selector:
    app: meilisearch
  ports:
    - protocol: TCP
      port: 7700
      targetPort: 7700
