apiVersion: v1
kind: Service
metadata:
    name: frontend-service
    namespace: promptheus
spec:
    selector:
        app: frontend
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
