apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: postgres-metrics
    namespace: team-promptheus
    labels:
        app: postgres
spec:
    selector:
        matchLabels:
            app: postgres
    endpoints:
    - port: monitoring
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
