apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: search-metrics
    namespace: team-promptheus
    labels:
        app: search
spec:
    selector:
        matchLabels:
            app: search
    endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s
