apiVersion: apps/v1
kind: Deployment
metadata:
    name: client
    namespace: team-promptheus
spec:
    replicas: 1
    selector:
        matchLabels:
            app: client
    template:
        metadata:
            labels:
                app: client
        spec:
            containers:
                - name: client
                  imagePullPolicy: Always
                  restartPolicy: Always
                  image: ghcr.io/aet-devops25/promptheus-client:main
                  ports:
                      - containerPort: 3000
                  securityContext:
                      runAsNonRoot: true
                      allowPrivilegeEscalation: false
                      readOnlyRootFilesystem: true
                      runAsUser: 1000
                      runAsGroup: 1000
                      privileged: false
                  livenessProbe:
                      httpGet:
                          path: /
                          port: 3000
                      initialDelaySeconds: 1
                      periodSeconds: 10
                      timeoutSeconds: 3
                      failureThreshold: 5

                  readinessProbe:
                      httpGet:
                          path: /
                          port: 3000
                      initialDelaySeconds: 1
                      periodSeconds: 10
                      timeoutSeconds: 3
                      failureThreshold: 5
                  resources:
                      requests:
                          cpu: 100m
                          memory: 10Mi
                      limits:
                          cpu: 500m
                          memory: 512Mi
