import fs from 'node:fs';
import app from './app.ts';

const spec = app.getOpenAPIDocument({
  openapi: '3.1.0',
  info: {
    title: 'LangChain AI Service API',
    version: '1.0.0',
    description: 'API for interacting with the LangChain AI service. Generated by Hono.',
  },
  servers: [
    {
      url: `http://localhost:${process.env.GENAI_PORT || 3003}`,
      description: 'Development server',
    },
  ],
});

fs.writeFileSync('./openapi.json', JSON.stringify(spec, null, 2));

console.log('✅ OpenAPI specification generated to openapi.json'); 