apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-pvc
    namespace: team-promptheus
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: meilisearch-pvc
    namespace: team-promptheus
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
