apiVersion: v1
kind: Service
metadata:
    name: client-service
    namespace: {{ $.Release.Namespace }}
    labels:
        app: client
        component: client-service
spec:
    selector:
        app: client
    ports:
        - protocol: TCP
          port: 8081
          targetPort: 8081
