apiVersion: v1
kind: Service
metadata:
  name: collector-service
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: contribution
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
