apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: {{ $.Release.Namespace }}
  labels:
    app: genai
    component: genai-service
spec:
  selector:
    app: genai
  ports:
    - name: http
      protocol: TCP
      port: 3003
      targetPort: 3003
