apiVersion: v1
kind: Service
metadata:
  name: meilisearch-service
  labels:
    app: meilisearch
    component: meilisearch-service
  namespace: { { $.Release.Namespace } }
spec:
  selector:
    app: meilisearch
  ports:
    - name: http
      protocol: TCP
      port: 7700
      targetPort: 7700
