apiVersion: v1
kind: Service
metadata:
    name: meilisearch-service
    labels:
      app: search
      component: meilisearch-service
    namespace: {{ $.Release.Namespace }}
spec:
    selector:
        app: meilisearch
    ports:
        - protocol: TCP
          port: 7700
          targetPort: 7700
