apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app: postgres
    component: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: monitoring
      protocol: TCP
      port: 9187
      targetPort: 9187
