apiVersion: v1
kind: Service
metadata:
    name: search-service
    namespace: {{ $.Release.Namespace }}
spec:
    selector:
        app: server
    ports:
        - protocol: TCP
          port: 8070
          targetPort: 8070
