apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app: search
    component: search-service
spec:
  selector:
    app: search
  ports:
    - name: http
      protocol: TCP
      port: 8070
      targetPort: 8070
