apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: {{ $.Release.Namespace }}
  labels:
    app: server
    component: server-service
spec:
  selector:
    app: server
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
