{{- $postgresPassword := .Values.secrets.postgresPassword | required "secrets.postgresPassword is required." -}}
{{- $meiliMasterKey := .Values.secrets.meiliMasterKey | required "secrets.meiliMasterKey is required." -}}
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:
    MEILI_MASTER_KEY: "{{ $meiliMasterKey }}"
    # postgres
    POSTGRES_PASSWORD: "{{ $postgresPassword }}"
    POSTGRES_USER: "postgres"
    POSTGRES_DB: "postgres"
    spring.datasource.url: jdbc:postgresql://postgres-service:5432/postgres
    {{ with .Values.secrets.openaiApiKey }}
    OPENAI_API_KEY: {{ . }}
    {{ end }}
    {{ with .Values.secrets.ollamaApiKey }}
    OLLAMA_API_KEY: {{ . }}
    {{ end }}
# TODO: set up secret for pull from repo and tls setup
