apiVersion: apps/v1
kind: Deployment
metadata:
    name: client
    namespace: team-promptheus
spec:
    replicas: 1
    selector:
        matchLabels:
            app: client
    template:
        metadata:
            labels:
                app: client
        spec:
            containers:
                - name: client
                  image: ghcr.io/aet-devops25/team-promptheus-client:latest
                  ports:
                      - containerPort: 3000
                  livenessProbe:
                      httpGet:
                          path: /
                          port: 3000
                      initialDelaySeconds: 1
                      periodSeconds: 10
                      timeoutSeconds: 3
                      failureThreshold: 5

                  readinessProbe:
                      httpGet:
                          path: /
                          port: 3000
                      initialDelaySeconds: 1
                      periodSeconds: 10
                      timeoutSeconds: 3
                      failureThreshold: 5
