apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring
  namespace: team-promptheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
      - name: monitoring
        image: grafana/otel-lgtm:latest
        ports:
        - containerPort: 3000
        - containerPort: 4317
        - containerPort: 4318
        env:
        - name: GF_PATHS_DATA
          value: /data/grafana
        volumeMounts:
        - name: grafana-data
          mountPath: /data/grafana
        - name: prometheus-data
          mountPath: /data/prometheus
        - name: loki-data
          mountPath: /data/loki
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus-pvc
      - name: loki-data
        persistentVolumeClaim:
          claimName: loki-pvc
