apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  namespace: promptheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
      - name: meilisearch
        image: getmeili/meilisearch
        ports:
        - containerPort: 7700
        envFrom:
        - configMapRef:
            name: meilisearch-config
        - secretRef:
            name: app-secrets
        volumeMounts:
        - name: meilisearch-data
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - curl
            - --silent
            - http://localhost:7700/health
          initialDelaySeconds: 1
          periodSeconds: 10
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - curl
            - --silent
            - http://localhost:7700/health
          initialDelaySeconds: 1
          periodSeconds: 10
          failureThreshold: 5
      volumes:
      - name: meilisearch-data
        persistentVolumeClaim:
          claimName: meilisearch-pvc
