apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: team-promptheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/aet-devops25/team-promptheus-frontend:latest
        ports:
        - containerPort: 8080
        livenessProbe:
            exec:
                command:
                - curl
                - -f
                - http://localhost:8080/actuator/health

          #livenessProbe:
          #  exec:
          #    command:
          #    - node
          #    - -e
          #    - "fetch('http://localhost:8080/').then(x=>x.status==200?process.exit(0):process.exit(1)).catch(()=>process.exit(1))"
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5

        readinessProbe:
          exec:
            command:
            - node
            - -e
            - "fetch('http://localhost:8080/').then(x=>x.status==200?process.exit(0):process.exit(1)).catch(()=>process.exit(1))"
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 5
