apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: team-promptheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: ghcr.io/aet-devops25/team-promptheus-server:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: server-config
        - secretRef:
            name: app-secrets
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8080/actuator/health
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8080/actuator/health
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 5
