apiVersion: apps/v1
kind: Deployment
metadata:
    name: client
    namespace: {{ $.Release.Namespace }}
spec:
    replicas: {{ .Values.defaultReplicas }}
    selector:
        matchLabels:
            app: client
    template:
        metadata:
            labels:
                app: client
        spec:
            containers:
                - name: client
                  imagePullPolicy: Always
                  image: ghcr.io/aet-devops25/promptheus-client:main
                  ports:
                      - containerPort: 8081
                  env:
                      - name: NEXT_PUBLIC_SERVER_API_URL
                        value: http://server-service:8080
                      - name: NEXT_PUBLIC_GENAI_API_URL
                        value: http://genai-service:3003
                      - name: NEXT_PUBLIC_SEARCH_API_URL
                        value: http://search-service:8070
                      - name: NEXT_PUBLIC_CONTRIBUTIONS_API_URL
                        value: http://contribution-service:8082
                  securityContext:
                      runAsNonRoot: true
                      allowPrivilegeEscalation: false
                      readOnlyRootFilesystem: true
                      runAsUser: 1000
                      runAsGroup: 1000
                      privileged: false
                  livenessProbe:
                      httpGet:
                          path: /
                          port: 8081
                      initialDelaySeconds: 1
                      periodSeconds: 10
                      timeoutSeconds: 3
                      failureThreshold: 5

                  readinessProbe:
                      httpGet:
                          path: /
                          port: 8081
                      initialDelaySeconds: 1
                      periodSeconds: 10
                      timeoutSeconds: 3
                      failureThreshold: 5
                  resources:
                      requests:
                          cpu: 100m
                          memory: 10Mi
                      limits:
                          cpu: 500m
                          memory: 512Mi
