apiVersion: apps/v1
kind: Deployment
metadata:
    name: genai
    namespace: {{ $.Release.Namespace }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: genai
    template:
        metadata:
            labels:
                app: genai
        spec:
            containers:
                - name: genai
                  imagePullPolicy: Always
                  image: ghcr.io/aet-devops25/promptheus-genai:main
                  ports:
                      - containerPort: 3003
                  securityContext:
                      runAsNonRoot: true
                      allowPrivilegeEscalation: false
                      readOnlyRootFilesystem: true
                      runAsUser: 1000
                      runAsGroup: 1000
                      privileged: false
                  envFrom:
                      - configMapRef:
                            name: genai-config
                  env:
                      # secrets
                      - name: MEILI_MASTER_KEY
                        valueFrom:
                            secretKeyRef:
                                name: app-secrets
                                key: MEILI_MASTER_KEY
                      {{ with .Values.secrets.ollamaApiKey }}
                      - name: OLLAMA_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: app-secrets
                                key: OLLAMA_API_KEY
                      {{ end }}
                      {{ with .Values.secrets.openaiApiKey }}
                      - name: OPENAI_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: app-secrets
                                key: OPENAI_API_KEY
                      {{ end }}
                      # routing
                      - name: MEILISEARCH_URL
                        value: http://meilisearch-service:7700
                      - name: OTEL_EXPORTER_OTLP_ENDPOINT
                        value: "http://otel-collector-service:4317"
                      - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
                        value: "http://otel-collector-service:4317/v1/traces"
                      - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
                        value: "http://otel-collector-service:4317/v1/metrics"
                      - name: OTEL_EXPORTER_OTLP_LOGGING_ENDPOINT
                        value: "http://otel-collector-service:4317/v1/logs"
                  command: ["sh", "-c", "uvicorn app:app --host 0.0.0.0 --port 3003"]
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: 3003
                      initialDelaySeconds: 1
                      periodSeconds: 10
                      timeoutSeconds: 3
                      failureThreshold: 5
                  readinessProbe:
                      httpGet:
                          path: /health
                          port: 3003
                      initialDelaySeconds: 1
                      periodSeconds: 10
                      timeoutSeconds: 3
                      failureThreshold: 5
                  resources:
                      requests:
                          cpu: 100m
                          memory: 256Mi
                      limits:
                          cpu: 2
                          memory: 2Gi
