apiVersion: apps/v1
kind: Deployment
metadata:
    name: server
    namespace: {{ $.Release.Namespace }}
spec:
    replicas: {{ .Values.defaultReplicas }}
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
                - name: server
                  imagePullPolicy: Always
                  image: ghcr.io/aet-devops25/promptheus-server:main
                  ports:
                      - containerPort: 8080
                  securityContext:
                      runAsNonRoot: true
                      allowPrivilegeEscalation: false
                      readOnlyRootFilesystem: false # JIT requires writing
                      runAsUser: 1000
                      runAsGroup: 1000
                      privileged: false
                  env:
                      # secrets
                      - name: spring.datasource.url
                        valueFrom:
                            secretKeyRef:
                                name: app-secrets
                                key: spring.datasource.url
                      - name: spring.datasource.username
                        valueFrom:
                            secretKeyRef:
                                name: app-secrets
                                key: POSTGRES_USER
                      - name: spring.datasource.password
                        valueFrom:
                            secretKeyRef:
                                name: app-secrets
                                key: POSTGRES_PASSWORD
                      # routing
                      - name: management.otlp.tracing.endpoint
                        value: http://monitoring-service:4318/v1/traces
                      - name: management.otlp.metrics.export.url
                        value: http://monitoring-service:4318/v1/metrics
                      - name: management.otlp.logging.endpoint
                        value: http://monitoring-service:4318/v1/logs
                  livenessProbe:
                      httpGet:
                          path: /actuator/health
                          port: 8080
                      initialDelaySeconds: 1
                      periodSeconds: 10
                      timeoutSeconds: 3
                      failureThreshold: 5
                  readinessProbe:
                      httpGet:
                          path: /actuator/health
                          port: 8080
                      initialDelaySeconds: 1
                      periodSeconds: 10
                      timeoutSeconds: 3
                      failureThreshold: 5
                  resources:
                      requests:
                          cpu: 100m
                          memory: 256Mi
                      limits:
                          cpu: 1
                          memory: 1Gi
