apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: contribution-metrics
    namespace: {{ $.Release.Namespace }}
    labels:
        app: contribution
spec:
    selector:
        matchLabels:
            app: contribution
    endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s
