apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-metrics
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app: monitoring
    release: {{ $.Release.Name }}
    prometheus: team-promptheus-prometheus
spec:
  selector:
    matchLabels:
      app: monitoring
  endpoints:
    - port: grafana
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
