apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: otel-collector-metrics
    namespace: "{{ $.Release.Namespace }}"
    labels:
        app: otel-collector
spec:
    selector:
        matchLabels:
            app: otel-collector
    endpoints:
    - port: prometheus
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
