apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-metrics
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app: postgres
    release: {{ $.Release.Name }}
    prometheus: team-promptheus-prometheus
spec:
  selector:
    matchLabels:
      app: postgres
  endpoints:
    - port: monitoring
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
