apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: server-metrics
    namespace: "{{ $.Release.Namespace }}"
    labels:
        app: server
spec:
    selector:
        matchLabels:
            app: server
    endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s
