package com.server.CommunicationObjects;

import com.server.persistence.entity.QuestionAnswer;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.Instant;
import lombok.Builder;

@Schema(description = "Answer provided by the AI for a user's question")
@Builder
public record QuestionAnswerConstruct(
    @Schema(
        description = "The answer text generated by the AI",
        example = "The system uses OAuth2 with JWT tokens for authentication",
        requiredMode = Schema.RequiredMode.REQUIRED,
        nullable = false
    )
    String answer,

    @Schema(
        description = "Timestamp when the answer was generated",
        example = "2023-01-16T09:15:30.456Z",
        requiredMode = Schema.RequiredMode.REQUIRED,
        nullable = false
    )
    Instant createdAt
) {
    public static QuestionAnswerConstruct from(QuestionAnswer a) {
        return QuestionAnswerConstruct.builder().answer(a.getAnswer()).createdAt(a.getCreatedAt()).build();
    }
}
