name: Contribution-collector CI/CD

on:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  contribution-checks:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:17
        env:
          TZ: Europe/Berlin
          PGDATA: /var/lib/postgresql/data/pgdata
          POSTGRES_PASSWORD: CHANGE_ME
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
      meilisearch:
        image: getmeili/meilisearch:latest
        ports:
          - 7700:7700
        env:
          MEILI_MASTER_KEY: CHANGE_ME_CHANGE_ME
          MEILI_ENV: development
        options: >-
          --health-cmd "curl --silent http://localhost:7700/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        gradleCommand: [test, bootJar]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: ${{ matrix.gradleCommand }} with Gradle
        run: gradle ${{ matrix.gradleCommand }}
        working-directory: contribution
        env:
          spring.datasource.url: jdbc:postgresql://db:5432/postgres
          spring.datasource.username: postgres
          spring.datasource.password: CHANGE_ME
          app.meiliMasterKey: CHANGE_ME_CHANGE_ME
          app.meiliHost: http://meilisearch:7700
  docker-build:
    uses: ./.github/workflows/_docker-build.yml
    needs:
      - contribution-checks
    with:
      image_suffix: contribution
      context: ./contribution
      dockerfile: Dockerfile
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write
  docker-init-build:
    uses: ./.github/workflows/_docker-build.yml
    needs:
      - contribution-checks
    with:
      image_suffix: ms-init
      context: ./
      dockerfile: Dockerfile.meiliinit
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write
