name: Search CI/CD

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  search-checks:
    runs-on: ubuntu-latest
    services:
      meilisearch:
        image: getmeili/meilisearch:latest
        ports:
          - 7700:7700
        env:
          MEILI_MASTER_KEY: CHANGE_ME_CHANGE_ME
          MEILI_ENV: development
        options: >-
          --health-cmd "curl --silent http://localhost:7700/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        gradleCommand: [test, bootJar]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: ${{ matrix.gradleCommand }} with Gradle
        run: gradle ${{ matrix.gradleCommand }}
        working-directory: search
        env:
          app.meiliMasterKey: CHANGE_ME_CHANGE_ME
          app.meiliHost: http://meilisearch:7700
  docker-build:
    uses: ./.github/workflows/_docker-build.yml
    needs:
      - search-checks
    with:
      image_suffix: search
      context: ./search
      dockerfile: Dockerfile
      openapi_url: http://localhost:8070/openapi
      healthcheck_url: http://localhost:8070/actuator/health
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
