name: Server CI/CD

on:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  server-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gradleCommand: [build, test]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: ${{ matrix.gradleCommand }} with Gradle
        run: gradle ${{ matrix.gradleCommand }}
        working-directory: server
  docker-build:
    uses: ./.github/workflows/_docker-build.yml
    needs:
      - server-checks
    with:
      image_suffix: client
      context: ./client
      dockerfile: Dockerfile
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write
