name: Webclient CI/CD

on:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  webclient-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run:  npm i --frozen-lockfile --strict-peer-dependencies
        working-directory: client
      - run: pnpm run lint
        working-directory: client
      - run: pnpm run type-check
        working-directory: webclient
  webclient-build:
    uses: ./.github/workflows/_docker-build.yml
    needs:
      - webclient-linting
    with:
      image_suffix: webclient
      context: ./webclient
      dockerfile: Dockerfile
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write
