apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
    name: application-health-alerts
    namespace: {{ $.Release.Namespace }}
    labels:
        app: prometheus
        role: alert-rules
spec:
    groups:
    - name: application-health
      rules:
      - alert: HighErrorRate
        expr: (sum(rate(http_requests_total{namespace="team-promptheus",status=~"5.."}[5m])) by (service) / sum(rate(http_requests_total{namespace="team-promptheus"}[5m])) by (service)) * 100 > 10
        for: 5m
        labels:
            severity: critical
        annotations:
            summary: "High error rate detected in {{`{{`}} $labels.service {{`}}`}}"
            description: "Service {{`{{`}} $labels.service {{`}}`}} has an error rate of {{`{{`}} $value {{`}}`}}% for more than 5 minutes"

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{namespace="team-promptheus"}[5m])) by (le, service)) > 2
        for: 10m
        labels:
            severity: warning
        annotations:
            summary: "High response time detected in {{`{{`}} $labels.service {{`}}`}}"
            description: "Service {{`{{`}} $labels.service {{`}}`}} 95th percentile response time is {{`{{`}} $value {{`}}`}}s for more than 10 minutes"

      - alert: ServiceDown
        expr: up{namespace="team-promptheus"} == 0
        for: 1m
        labels:
            severity: critical
        annotations:
            summary: "Service {{`{{`}} $labels.job {{`}}`}} is down"
            description: "Service {{`{{`}} $labels.job {{`}}`}} has been down for more than 1 minute"
