apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
    name: node-health-alerts
    namespace: {{ $.Release.Namespace }}
    labels:
        app: prometheus
        role: alert-rules
spec:
    groups:
    - name: node-health
      rules:
      - alert: NodeNotReady
        expr: kube_node_status_ready{condition="false"} == 1
        for: 5m
        labels:
            severity: critical
        annotations:
            summary: "Node {{`{{`}} $labels.node {{`}}`}} is not ready"
            description: "Node {{`{{`}} $labels.node {{`}}`}} has been in NotReady state for more than 5 minutes"

      - alert: NodeHighCPU
        expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 85
        for: 10m
        labels:
            severity: warning
        annotations:
            summary: "High CPU usage on node {{`{{`}} $labels.instance {{`}}`}}"
            description: "Node {{`{{`}} $labels.instance {{`}}`}} CPU usage is {{`{{`}} $value {{`}}`}}% for more than 10 minutes"

      - alert: NodeHighMemory
        expr: ((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100 > 90
        for: 10m
        labels:
            severity: warning
        annotations:
            summary: "High memory usage on node {{`{{`}} $labels.instance {{`}}`}}"
            description: "Node {{`{{`}} $labels.instance {{`}}`}} memory usage is {{`{{`}} $value {{`}}`}}% for more than 10 minutes"

      - alert: NodeDiskSpaceHigh
        expr: ((node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes) * 100 > 85
        for: 5m
        labels:
            severity: warning
        annotations:
            summary: "High disk usage on node {{`{{`}} $labels.instance {{`}}`}}"
            description: "Node {{`{{`}} $labels.instance {{`}}`}} disk usage is {{`{{`}} $value {{`}}`}}% on mountpoint {{`{{`}} $labels.mountpoint {{`}}`}}"
